let world0 = {
    world: {"data":{"row":"11","col":"18"},"level":{"303":{"wall":"blank","meta":["none","none"]},"304":{"wall":"blank","meta":["none","none"]},"305":{"wall":"blank","meta":["none","none"]},"309":{"wall":"blank","meta":["none","none"]},"310":{"wall":"blank","meta":["none","none"]},"311":{"wall":"blank","meta":["none","none"]},"312":{"wall":"blank","meta":["none","none"]},"313":{"wall":"blank","meta":["none","none"]},"314":{"wall":"blank","meta":["none","none"]},"315":{"wall":"blank","meta":["none","none"]},"403":{"wall":"blank","meta":["none","none"]},"404":{"wall":"blank","item":"arrow","meta":["none","none"]},"405":{"wall":"blank"},"406":{"wall":"enter","meta":["world0","level1"],"info":"1"},"407":{"wall":"enter","meta":["world0","level2"],"info":"2"},"408":{"wall":"enter","meta":["world0","level3"],"info":"3"},"409":{"wall":"blank","meta":["none","none"]},"410":{"wall":"enter","meta":["world0","level4"],"info":"4"},"411":{"wall":"blank","meta":["none","none"]},"412":{"wall":"enter","meta":["world0","level5"],"info":"5"},"413":{"wall":"blank","meta":["none","none"]},"414":{"wall":"enter","meta":["world0","level6"],"info":"6"},"415":{"wall":"blank","meta":["none","none"]},"416":{"wall":"win","meta":["world","world"],"info":"W"},"503":{"wall":"blank","meta":["none","none"]},"504":{"wall":"blank","meta":["none","none"]},"505":{"wall":"blank","meta":["none","none"]},"509":{"wall":"blank","meta":["none","none"]},"510":{"wall":"blank","meta":["none","none"]},"511":{"wall":"blank","meta":["none","none"]},"512":{"wall":"blank","meta":["none","none"]},"513":{"wall":"blank","meta":["none","none"]},"514":{"wall":"blank"},"515":{"wall":"blank","meta":["none","none"]},"612":{"wall":"blank","meta":["none","none"]},"711":{"wall":"blank","meta":["none","none"]},"712":{"wall":"blank","meta":["none","none"]},"713":{"wall":"blank","meta":["none","none"]},"811":{"wall":"blank","meta":["none","none"]},"812":{"wall":"enter","meta":["world0","level7"],"info":"7!"},"813":{"wall":"blank","meta":["none","none"]},"911":{"wall":"blank","meta":["none","none"]},"912":{"wall":"blank","meta":["none","none"]},"913":{"wall":"blank","meta":["none","none"]}}},

    level1: {"data":{"row":"8","col":"11"},"level":{"306":{"item":"mine"},"406":{"wall":"blank"},"506":{"wall":"blank","item":"clue","data":"1"},"603":{"wall":"blank","item":"arrow","data":true},"604":{"wall":"blank"},"605":{"wall":"blank"},"606":{"wall":"blank"},"607":{"wall":"blank"},"608":{"wall":"blank"},"609":{"wall":"win","meta":["world0","world"],"info":"1"}}},

    level2: {"data":{"row":"8","col":"9"},"level":{"304":{"item":"mine"},"306":{"item":"mine"},"403":{"wall":"blank","item":"arrow"},"404":{"wall":"blank","item":"clue","data":"1"},"405":{"wall":"blank"},"406":{"wall":"blank"},"407":{"wall":"win","meta":["world0","world"],"info":"2"},"503":{"wall":"blank"},"504":{"wall":"blank","item":"clue","data":"2"},"505":{"wall":"blank","item":"box"},"506":{"wall":"blank"},"603":{"wall":"blank"},"604":{"wall":"blank"},"605":{"wall":"blank"},"606":{"wall":"blank"}}},

    level3: {"data":{"row":"9","col":"9"},"level":{"303":{"wall":"win","meta":["world","level9"],"info":"3"},"305":{"item":"clue","data":"0"},"307":{"item":"mine"},"403":{"wall":"blank","item":"arrow"},"404":{"wall":"blank"},"405":{"wall":"blank","item":"mine"},"406":{"wall":"blank"},"407":{"wall":"blank"},"503":{"wall":"blank"},"504":{"wall":"blank","item":"clue","data":"1"},"505":{"wall":"blank"},"506":{"wall":"blank","item":"clue","data":"2"},"507":{"wall":"blank"},"603":{"wall":"blank"},"604":{"wall":"blank"},"605":{"wall":"blank"},"606":{"wall":"blank"},"607":{"wall":"blank"},"703":{"wall":"blank"},"704":{"wall":"blank"}}},

    level4: {"data":{"row":"11","col":"9"},"level":{"305":{"item":"clue","data":"2"},"308":{"data":"1"},"403":{"wall":"blank"},"404":{"wall":"blank"},"405":{"wall":"blank","data":"2"},"406":{"wall":"blank","item":"mine"},"407":{"wall":"blank","data":"3"},"503":{"wall":"blank"},"504":{"wall":"blank","item":"mine","data":"4"},"505":{"wall":"blank","data":"2"},"506":{"wall":"blank","item":"mine","data":"2"},"507":{"wall":"blank"},"603":{"wall":"blank"},"604":{"wall":"blank","item":"clue","data":"1"},"605":{"wall":"blank","data":"4"},"606":{"wall":"blank","data":"4"},"607":{"wall":"blank","item":"mine"},"703":{"wall":"blank"},"704":{"wall":"blank"},"705":{"wall":"blank","item":"clue","data":"4"},"706":{"wall":"blank"},"707":{"wall":"blank","item":"mine"},"803":{"wall":"blank","item":"arrow"},"804":{"wall":"blank"},"805":{"wall":"blank"},"806":{"wall":"blank"},"807":{"wall":"blank"},"903":{"wall":"win","meta":["world0","world"],"info":"4"},"904":{"wall":"blank"},"905":{"wall":"blank","data":"2"},"906":{"wall":"blank","data":"2"},"907":{"wall":"blank","data":"2"}}},

    level5: {"data":{"row":"11","col":"15"},"level":{"304":{"item":"mine"},"312":{"item":"mine"},"403":{"item":"mine"},"404":{"wall":"blank","item":"arrow"},"405":{"wall":"blank"},"406":{"wall":"blank"},"407":{"wall":"blank"},"408":{"wall":"blank"},"409":{"wall":"blank"},"410":{"wall":"blank"},"411":{"wall":"blank"},"412":{"wall":"blank"},"413":{"item":"mine"},"504":{"wall":"blank"},"506":{"wall":"blank","item":"clue","data":"3"},"508":{"wall":"blank","item":"clue","data":"1"},"510":{"wall":"blank","item":"clue","data":"2"},"512":{"wall":"blank"},"604":{"wall":"blank"},"606":{"wall":"blank","item":"clue","data":"0"},"608":{"wall":"blank","item":"clue","data":"2"},"610":{"wall":"blank","item":"clue","data":"1"},"612":{"wall":"blank"},"703":{"item":"mine"},"704":{"wall":"blank"},"706":{"wall":"blank","item":"clue","data":"1"},"708":{"wall":"blank","item":"clue","data":"1"},"710":{"wall":"blank","item":"clue","data":"3"},"712":{"wall":"blank"},"713":{"item":"mine"},"803":{"item":"mine"},"804":{"wall":"blank"},"805":{"wall":"blank"},"806":{"wall":"blank"},"807":{"wall":"blank"},"808":{"wall":"blank"},"809":{"wall":"blank"},"810":{"wall":"blank"},"811":{"wall":"blank"},"812":{"wall":"blank"},"813":{"item":"mine"},"904":{"item":"mine"},"908":{"wall":"win","meta":["world0","world"],"info":"5"},"912":{"item":"mine"}}},

    level6: {"data":{"row":"10","col":"12"},"level":{"304":{"wall":"blank"},"305":{"wall":"blank"},"308":{"wall":"blank"},"309":{"wall":"blank"},"310":{"wall":"blank"},"404":{"wall":"blank","item":"box"},"405":{"wall":"blank"},"406":{"wall":"blank"},"407":{"wall":"blank"},"408":{"wall":"blank"},"409":{"wall":"blank","item":"clue","data":"1"},"410":{"wall":"blank"},"504":{"wall":"blank"},"508":{"wall":"blank"},"603":{"wall":"blank","item":"arrow","data":true},"604":{"wall":"blank"},"605":{"wall":"blank","item":"mine"},"606":{"wall":"win","item":"clue","data":"2","meta":["world0","world"],"info":"6"},"607":{"wall":"blank","item":"mine"},"608":{"wall":"blank"},"609":{"wall":"blank"},"704":{"wall":"blank"},"708":{"wall":"blank"},"709":{"wall":"blank","item":"clue","data":"1"},"710":{"wall":"blank"},"804":{"wall":"blank"},"805":{"wall":"blank"},"806":{"wall":"blank"},"807":{"wall":"blank"},"808":{"wall":"blank"},"809":{"wall":"blank"},"810":{"wall":"blank"}}},

    level7: {"data":{"row":"11","col":"12"},"level":{"305":{"item":"mine"},"306":{"item":"mine"},"307":{"item":"mine"},"403":{"item":"clue","data":"0"},"405":{"wall":"blank"},"406":{"wall":"blank"},"407":{"wall":"blank","item":"clue","data":"3"},"408":{"wall":"blank"},"409":{"wall":"blank"},"410":{"wall":"blank"},"503":{"wall":"blank"},"504":{"wall":"blank"},"505":{"wall":"blank","item":"mine"},"506":{"wall":"blank"},"507":{"wall":"blank"},"508":{"wall":"blank"},"509":{"wall":"blank"},"510":{"wall":"win","meta":["world0","world"],"info":"7!"},"603":{"wall":"blank"},"604":{"wall":"blank","item":"clue","data":"3"},"605":{"wall":"blank","item":"mine"},"606":{"wall":"blank","item":"clue","data":"3"},"607":{"wall":"blank","item":"clue","data":"1"},"608":{"wall":"blank"},"609":{"wall":"blank"},"610":{"wall":"blank","item":"box","data":"1"},"703":{"wall":"blank"},"704":{"wall":"blank"},"705":{"wall":"blank","item":"clue","data":"2"},"706":{"wall":"blank"},"707":{"wall":"blank"},"708":{"item":"mine"},"710":{"wall":"blank","data":"1"},"803":{"wall":"blank","item":"arrow"},"804":{"wall":"blank"},"805":{"wall":"blank"},"806":{"wall":"blank"},"807":{"item":"mine"},"907":{"item":"clue","data":"1"}}},
}

let world = {
    world: {"data":{"row":"9","col":"17"},"level":{"303":{"wall":"blank"},"304":{"wall":"blank"},"305":{"wall":"blank"},"307":{"wall":"blank"},"308":{"wall":"blank"},"309":{"wall":"blank"},"313":{"wall":"blank"},"314":{"wall":"blank"},"404":{"wall":"blank"},"407":{"wall":"blank"},"410":{"wall":"enter","meta":["world1A","world"],"info":"W1A"},"412":{"wall":"blank"},"415":{"wall":"blank"},"504":{"wall":"blank"},"507":{"wall":"blank"},"508":{"wall":"blank"},"509":{"wall":"blank"},"512":{"wall":"blank"},"604":{"wall":"blank"},"607":{"wall":"blank"},"610":{"wall":"enter","meta":["world1B","world"],"info":"W1B"},"612":{"wall":"blank"},"615":{"wall":"blank"},"704":{"wall":"blank","item":"arrow"},"705":{"wall":"enter","meta":["world0","world"],"info":"W0"},"707":{"wall":"blank"},"708":{"wall":"blank"},"709":{"wall":"blank"},"713":{"wall":"blank"},"714":{"wall":"blank"}}},
}

let All = {
    world: world,
    world0: world0,
}